# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_Big_integer', [dirname(__file__)])
        except ImportError:
            import _Big_integer
            return _Big_integer
        if fp is not None:
            try:
                _mod = imp.load_module('_Big_integer', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _Big_integer = swig_import_helper()
    del swig_import_helper
else:
    import _Big_integer
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class Big_integer(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Big_integer, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Big_integer, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _Big_integer.new_Big_integer(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _Big_integer.delete_Big_integer
    __del__ = lambda self: None

    def GetString(self):
        return _Big_integer.Big_integer_GetString(self)

    def ReadFromTextFile(self, FileName):
        return _Big_integer.Big_integer_ReadFromTextFile(self, FileName)

    def WriteToTextFile(self, FileName):
        return _Big_integer.Big_integer_WriteToTextFile(self, FileName)

    def ReadFromBin(self, FileName):
        return _Big_integer.Big_integer_ReadFromBin(self, FileName)

    def WriteToBin(self, FileName):
        return _Big_integer.Big_integer_WriteToBin(self, FileName)

    def __gt__(self, Y):
        return _Big_integer.Big_integer___gt__(self, Y)

    def __ge__(self, Y):
        return _Big_integer.Big_integer___ge__(self, Y)

    def __lt__(self, Y):
        return _Big_integer.Big_integer___lt__(self, Y)

    def __le__(self, Y):
        return _Big_integer.Big_integer___le__(self, Y)

    def __eq__(self, Y):
        return _Big_integer.Big_integer___eq__(self, Y)

    def __ne__(self, Y):
        return _Big_integer.Big_integer___ne__(self, Y)

    def __add__(self, RValue):
        return _Big_integer.Big_integer___add__(self, RValue)

    def __neg__(self):
        return _Big_integer.Big_integer___neg__(self)

    def __sub__(self, RValue):
        return _Big_integer.Big_integer___sub__(self, RValue)

    def __mul__(self, RValue):
        return _Big_integer.Big_integer___mul__(self, RValue)

    def __div__(self, RValue):
        return _Big_integer.Big_integer___div__(self, RValue)

    def __mod__(self, RValue):
        return _Big_integer.Big_integer___mod__(self, RValue)

    def __xor__(self, RValue):
        return _Big_integer.Big_integer___xor__(self, RValue)
Big_integer_swigregister = _Big_integer.Big_integer_swigregister
Big_integer_swigregister(Big_integer)


def Pow(X, Y, M):
    return _Big_integer.Pow(X, Y, M)
Pow = _Big_integer.Pow
# This file is compatible with both classic and new-style classes.


